/* SimpleCNN INT8 inference for embedded deployment */
/* Generated by Malak Platform */
/* Model: SimpleCNN (Fashion-MNIST), ~458K params */
/* NOTE: Weight arrays are generated by embedded/scripts/export_model.py */
/* This file contains the inference logic with placeholder weights. */
/* Run export_model.py after training to populate real weights. */

#include "cifar10_model.h"
#include <string.h>

/* Placeholder: weights go here after export_model.py runs */
/* Conv1: 32 filters, 1 in_ch, 3x3 = 288 int8 weights */
static const int8_t conv1_weight[288] = {0};
/* Conv2: 64 filters, 32 in_ch, 3x3 = 18432 int8 weights */
static const int8_t conv2_weight[18432] = {0};
/* Conv3: 64 filters, 64 in_ch, 3x3 = 36864 int8 weights */
static const int8_t conv3_weight[36864] = {0};
/* FC1: 128 out, 3136 in = 401408 int8 weights */
static const int8_t fc1_weight[401408] = {0};
/* FC2: 10 out, 128 in = 1280 int8 weights */
static const int8_t fc2_weight[1280] = {0};

static int model_initialized = 0;

int model_init(void) {
    model_initialized = 1;
    return 0;
}

/* Naive but correct INT8 conv2d */
static void conv2d_int8(
    const int8_t* weight, float scale,
    const float* input, float* output,
    int in_ch, int out_ch, int h, int w, int ksize, int pad
) {
    for (int oc = 0; oc < out_ch; oc++) {
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                float sum = 0.0f;
                for (int ic = 0; ic < in_ch; ic++) {
                    for (int ky = 0; ky < ksize; ky++) {
                        for (int kx = 0; kx < ksize; kx++) {
                            int iy = y + ky - pad;
                            int ix = x + kx - pad;
                            if (iy >= 0 && iy < h && ix >= 0 && ix < w) {
                                float val = input[ic * h * w + iy * w + ix];
                                int widx = oc * in_ch * ksize * ksize +
                                           ic * ksize * ksize + ky * ksize + kx;
                                sum += val * (weight[widx] * scale);
                            }
                        }
                    }
                }
                output[oc * h * w + y * w + x] = sum;
            }
        }
    }
}

static void relu_inplace(float* data, int n) {
    for (int i = 0; i < n; i++)
        if (data[i] < 0.0f) data[i] = 0.0f;
}

static void maxpool2x2(const float* in, float* out, int ch, int h, int w) {
    int oh = h / 2, ow = w / 2;
    for (int c = 0; c < ch; c++) {
        for (int y = 0; y < oh; y++) {
            for (int x = 0; x < ow; x++) {
                float m = in[c*h*w + 2*y*w + 2*x];
                float v;
                v = in[c*h*w + 2*y*w + 2*x+1]; if (v > m) m = v;
                v = in[c*h*w + (2*y+1)*w + 2*x]; if (v > m) m = v;
                v = in[c*h*w + (2*y+1)*w + 2*x+1]; if (v > m) m = v;
                out[c*oh*ow + y*ow + x] = m;
            }
        }
    }
}

static void fc_int8(
    const int8_t* weight, float scale,
    const float* input, float* output,
    int in_dim, int out_dim
) {
    for (int o = 0; o < out_dim; o++) {
        float sum = 0.0f;
        for (int i = 0; i < in_dim; i++)
            sum += input[i] * (weight[o * in_dim + i] * scale);
        output[o] = sum;
    }
}

/* Scratch buffers */
static float buf_a[64 * 28 * 28];
static float buf_b[64 * 28 * 28];

int model_infer(const uint8_t* input, float* output) {
    if (!model_initialized) return -1;
    if (!input || !output) return -1;

    /* Normalize: uint8 -> float, Fashion-MNIST stats */
    float* inp = buf_a;
    for (int i = 0; i < INPUT_SIZE; i++)
        inp[i] = (input[i] / 255.0f - 0.2860f) / 0.3530f;

    /* Conv1: [1,28,28] -> [32,28,28] + ReLU */
    conv2d_int8(conv1_weight, SCALE_CONV1, inp, buf_b, 1, 32, 28, 28, 3, 1);
    relu_inplace(buf_b, 32 * 28 * 28);
    /* MaxPool: [32,28,28] -> [32,14,14] */
    maxpool2x2(buf_b, buf_a, 32, 28, 28);

    /* Conv2: [32,14,14] -> [64,14,14] + ReLU */
    conv2d_int8(conv2_weight, SCALE_CONV2, buf_a, buf_b, 32, 64, 14, 14, 3, 1);
    relu_inplace(buf_b, 64 * 14 * 14);
    /* MaxPool: [64,14,14] -> [64,7,7] */
    maxpool2x2(buf_b, buf_a, 64, 14, 14);

    /* Conv3: [64,7,7] -> [64,7,7] + ReLU */
    conv2d_int8(conv3_weight, SCALE_CONV3, buf_a, buf_b, 64, 64, 7, 7, 3, 1);
    relu_inplace(buf_b, 64 * 7 * 7);

    /* FC1: [3136] -> [128] + ReLU */
    fc_int8(fc1_weight, SCALE_FC1, buf_b, buf_a, 64*7*7, 128);
    relu_inplace(buf_a, 128);

    /* FC2: [128] -> [10] */
    fc_int8(fc2_weight, SCALE_FC2, buf_a, output, 128, 10);

    return 0;
}

size_t model_get_memory_size(void) {
    return sizeof(buf_a) + sizeof(buf_b) + INPUT_SIZE + NUM_CLASSES * sizeof(float);
}

int model_argmax(const float* output) {
    int max_idx = 0;
    float max_val = output[0];
    for (int i = 1; i < NUM_CLASSES; i++) {
        if (output[i] > max_val) {
            max_val = output[i];
            max_idx = i;
        }
    }
    return max_idx;
}
